# handler
## isa idk if I sent the client object correctly, check it and if it's not correct fix it thanks Mr isa.
## To Do
- add optional args
- fix 
```
Task exception was never retrieved
future: <Task finished name='Acord event dispatch: message' coro=<App.on_message() done, defined at c:\Users\dafty\Documents\GitHub\handler\handler\main.py:27> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "c:\Users\dafty\Documents\GitHub\handler\handler\main.py", line 39, in on_message
    dictionary_of_arguments[item] = arguments.split()[functionArguments.index(item)]
IndexError: list index out of range
```
